# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:https://mengalong.github.io/
url: https://mengalong.github.io/
date_format: "ordinal"
title: Mengalong
subtitle: "人生在勤,不索何获"
description: "MengAlong的个人博客"
keywords: MengAlong
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Along Meng
organization: Freelance
organization_url: 
github_username: mengalong
location: Xi'an, China
email: alongmeng@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mengalong/mengalong.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mengalong
    repo: blog-comments
    oauth:
        client_id: 3240a5b831da711d5b1d
        client_secret: eeb0f32703c8347018c51b058b61d5a48da70d1a
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mengalong
    repo: blog-comments
    clientID: 3240a5b831da711d5b1d
    clientSecret: eeb0f32703c8347018c51b058b61d5a48da70d1a
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 
